databases:
  - name: bingo
    plan: free
    databaseName: bingo
    user: bingo

services:
  - type: web
    plan: free
    name: ootbingo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ootbingo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bingo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4